name: the place where workflow upload shit

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: eat fat fish
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: drop brain
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 8
          cache: "gradle"
      - name: get low IQ
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: kill myse1f
        run: ./gradlew setupCiWorkspace && ./gradlew build
      - name: go to hell
        run: mv build/libs/Client-*.jar build/libs/Client-${{ steps.vars.outputs.sha_short }}.jar
      - name: done
        uses: actions/upload-artifact@v2
        with:
          name: Client
          path: build/libs/Client-${{ steps.vars.outputs.sha_short }}.jar
